// <auto-generated />
namespace Vendas_2022._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Vendas_5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vendas_5));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240137319_Vendas_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
